apiVersion: 1

datasources:
  - name: Kafka
    type: hamedkarbasi93-kafka-datasource
    access: proxy
    editable: true
    jsonData:
      bootstrapServers: "10.148.0.4:9092"
      securityProtocol: "PLAINTEXT"
